name = "Freenect"
uuid = "3da711cf-ac70-47ad-bd8d-7cd93f6093d7"
authors = ["dmillard <dmillard10@gmail.com> and contributors"]
version = "0.1.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
libfreenect_jll = "05d52523-c636-5a6c-8a6a-526edab90d71"

[compat]
DocStringExtensions = "0.8"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
